### ISSUE TITLE
Show an error when there is an Internet issue

### ISSUE THREAD

**Issue by louis-paul** [ProcessOut/processout-javascript-modal#2]
Right now, nothing specific happens when the user clicks on a button and is offline, which could confuse some. An actual error message would be great.

**Comment by manuel-huez** [comment]
When no internet connection is found, the javascript modal code won't be triggered and will redirect the user to the actual checkout page. The user should then be able to see there is no available internet connection. I find this behaviour to be sufficient for this issue; would like your input on it.

**Comment by louis-paul** [comment]
The only issue I have with the current approach is the delay (~5 sec.) before the user gets redirected.

**Comment by manuel-huez** [comment]
Reduced this delay to 1 second. https://github.com/ProcessOut/processout-javascript-modal/commit/ed8e19a1429300235c7528f04a2707174a4ef4f9

**Comment by louis-paul** [comment]
:+1:
